### ISSUE TITLE
show message  "Already up-to-date"

### ISSUE THREAD

**Issue by hyuraku** [Homebrew/homebrew-livecheck#1140]
I guess better show any message link `brew update` When all formulae are newer version in the upstream ( or they are updated)

```bash
$ brew update
Already up-to-date.
```

**Comment by samford** [comment]
`brew update` uses an "Already up-to-date" message because there isn't any output when everything is up-to-date. Showing a message makes it clear that everything's working properly but there was no work to be done.

By default, livecheck will show output for any formulae it checks, so it's not a concern as long as livecheck has formulae to check:

```
$ brew livecheck
a2ps : 4.14 ==> 4.14
activemq : 5.16.0 ==> 5.16.0
```

However, there are a couple situations where livecheck won't display any output and it would be helpful to have a message or error in those cases. I've created a PR to address this, if you would like to take a look: #1149

Let me know if you were thinking of any other situations that my PR doesn't already address.

**Comment by hyuraku** [comment]
@samford 
Thank you for all you've taught me. I understood the different `brew update` and `brew livecheck`.
I would like to check https://github.com/Homebrew/homebrew-livecheck/pull/1149 .
