### ISSUE TITLE
brew livecheck --installed stopped working

### ISSUE THREAD

**Issue by loganrosen** [Homebrew/homebrew-livecheck#1251]
As of a recent change, it appears that `brew livecheck --installed` has stopped working:
```
lrosen@lrosen-mn1 ~> brew livecheck --installed
Error: No formulae to check.
```

I definitely have installed formulae to check:
```
lrosen@lrosen-mn1 ~> brew list
apr		duti		git		oniguruma	perl		rsync		utf8proc	zstd
apr-util	fish		jq		openssl@1.1	popt		sqlite		xxhash
brewin		gettext		lz4		pcre2		readline	subversion	xz
```

I was able to pinpoint #1239 as the commit where this stopped functioning (cc @dawidd6).

**Comment by samford** [comment]
I'm fully up to date and `brew livecheck --installed` is working for me. This may simply be the recent change in `CLI::Parser` that briefly broke our CLI arg parsing today (before the fix in #1249).

Try doing a `brew update` and see if that fixes it for you.

**Comment by SMillerDev** [comment]
@loganrosen what does `brew config` day for you?

**Comment by loganrosen** [comment]
It's not working for me even after running a `brew update`. Here's the output of `brew config`:
```
HOMEBREW_VERSION: 2.4.9
ORIGIN: https://github.com/Homebrew/brew
HEAD: e6b066a3d9fc5435009428fcd2855fddf9b455c0
Last commit: 6 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: cef7c62b8d9c541c3d2af4e23682a2ec730f75db
Core tap last commit: 38 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_MAKE_JOBS: 16
CPU: 16-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 12.0 build 1200
Git: 2.28.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 1.8.0_212, 1.8.0_172-zulu-8.30.0.2, 1.8.0_172, 1.8.0_121, 1.8.0_72, 1.8.0_40, 1.8.0_05, 1.7.0_51
macOS: 10.15.6-x86_64
CLT: 12.0.0.0.1.1595091463
Xcode: N/A
```

**Comment by samford** [comment]
Ah, it makes sense now looking at your `brew config` output.

#1239 relies on a commit in Homebrew/brew that isn't yet in a tagged version. It may have been better to wait until the next Homebrew/brew release tag to merge that PR.

It's easy to forget in this context, as most folks who use `brew livecheck` have also run a `dev-cmd` at some point, so they get the latest commits in Homebrew/brew on `brew update` (instead of the latest tagged release). `brew livecheck` will be a `dev-cmd` once it's integrated into Homebrew/brew (sometime in the next few weeks), so we won't have to worry about this after that point.

Until there's a new Homebrew/brew release, the easiest solution may be to go into your local `homebrew-livecheck` tap and check out the commit before this change (941c517a17b016d3bb36bee5ab3244892bff3f75). There aren't going to be notable changes in this repository in the interim time (due to the ongoing Homebrew/brew migration), so you're unlikely to miss anything meaningful.

Alternatively, if you're interested in using the latest development version of Homebrew, you can [set the `HOMEBREW_DEVELOPER` environment variable to `1`](https://docs.brew.sh/Releases). To my understanding, this should get you on to the latest Homebrew/brew commit, which would fix the issue.

**Comment by samford** [comment]
Homebrew/brew version [2.4.10](https://github.com/Homebrew/brew/releases/tag/2.4.10) has been tagged and includes the relevant changes discussed here. I tested `brew livecheck --installed` on 2.4.10 and it appears to be working properly, so doing a `brew update` should resolve this for you now.

**Comment by loganrosen** [comment]
Confirmed, thanks so much!
