### ISSUE TITLE
GNOME releases with an odd minor version are development releases

### ISSUE THREAD

**Issue by Bo98** [Homebrew/homebrew-livecheck#300]
```
$ brew livecheck atk
atk (guessed) : 2.34.1 ==> 2.35.1
```

This goes against the audit check, which disallows 2.35.x: https://github.com/Homebrew/brew/blob/bcb8f4da5f48bb4ad96c1c66af0a3b5996f711d1/Library/Homebrew/dev-cmd/audit.rb#L782

Note however that there are exceptions: https://github.com/Homebrew/brew/blob/bcb8f4da5f48bb4ad96c1c66af0a3b5996f711d1/Library/Homebrew/dev-cmd/audit.rb#L751-L756

**Comment by samford** [comment]
I've been meaning to get around to fixing this. I had noticed this issue in the past and created a tentative solution but I haven't yet incorporated it into livecheck because I was looking for all the formulae that shouldn't be restricted in this manner. I had found a few myself but, last I left this, I hadn't gotten around to finding them all.

It looks like the `gnome_devel_whitelist` is exactly what I was looking for. Is it possible to access that array from within livecheck's heuristic or would I have to manually duplicate it?

I'll work on getting this together into a PR when I get a chance in a bit.

**Comment by Bo98** [comment]
> Is it possible to access that array from within livecheck's heuristic or would I have to manually duplicate it?

As it currently is, you can't access it directly. However having to update two repos constantly for exceptions would suck. I'm sure something can be worked out.

With that said, it's worth noting that entries on that list are currently version pinned. I don't know if there's a particular reason for that. For example, if `gtk-mac-integration` 2.1.4 came out tomorrow, should it be updated?

**Comment by samford** [comment]
It sounds like we'll just have to live with having this information in two places for the moment and address it in the future if/when we can. I've run out of time today but I'll try to work on integrating this with my existing solution and getting a PR up in the next day or two.

I often see @tschoonj working on GNOME-related formulae, so he may have an idea about why those formulae are pinned to specific versions.
