### ISSUE TITLE
calicoctl release process issue

### ISSUE THREAD

**Issue by chenrui333** [Homebrew/homebrew-livecheck#547]
calicoctl has very interesting release process, i.e. tagging the same commit with different release tags.

Details are in [here](https://github.com/projectcalico/calicoctl/issues/2115) and [here](https://github.com/projectcalico/calicoctl/issues/2072).

### Expected

We should exclude reporting the new release for `calicoctl` when the commit hash is the same.

**Comment by samford** [comment]
If we had livecheck artificially report an older version as newest based on the commit hash (e.g., returning 3.13.0 since 3.13.0, 3.13.1, 3.13.2, and 3.13.3 all use the same commit), this could lead users to think the check is broken (e.g., "3.13.3 is available but livecheck is reporting 3.13.0 as newest"). This is especially the case at present because the current version in the formula is 3.13.1 and livecheck would give 3.13.0 as newest, making it seem like there's an issue.

I can't think of a situation where it's appropriate to artificially restrict livecheck from reporting newer versions and this is true here. Rather, I think it would be better to deal with this by adding a comment above the `url` in the formula explaining the situation (e.g., `# Only update the version when the commit hash changes as well`). We have comments like these in other formulae for other reasons, so it makes sense to me.

Of course, this puts the onus on maintainers and contributors to be careful when creating version updates for `calicoctl` but this is already true for all formulae. Folks shouldn't just run livecheck and then do a quick `brew bump-formula-pr` without paying attention to what they're doing (or building/testing the formula locally before creating the PR). Anyone who isn't rushing through this would see that the `revision` hasn't changed and the comment would prevent them from creating an unnecessary PR.

When I'm going through livecheck output, I have to keep mental notes about which versions are actually newer and which should be avoided due to either upstream weirdness (like this) or Homebrew-specific issues. However, adding artificial restrictions to avoid seeing newer versions isn't an appropriate solution to me.

**Comment by SMillerDev** [comment]
This should be an audit (if it isn't already)

**Comment by MikeMcQuaid** [comment]
Closing for now but can be moved or reopened in Homebrew/brew if it applies to the new `brew livecheck` there.
