### ISSUE TITLE
sonarqube-lts: Unable to get versions

### ISSUE THREAD

**Issue by chenrui333** [Homebrew/homebrew-livecheck#560]
```
$ brew livecheck sonarqube
sonarqube : 8.2.0.32929 ==> 8.3.0.34182

$ brew livecheck sonarqube-lts
Error: sonarqube-lts: Unable to get versions
```

---

relates to 
- sonarqube, https://github.com/Homebrew/homebrew-core/pull/54058
- sonarqube-lts, https://github.com/Homebrew/homebrew-core/pull/54059

**Comment by samford** [comment]
Since they don't distinguish between current and LTS releases on the [index page for archives](https://binaries.sonarsource.com/Distribution/sonarqube/), it looks like we'll have to write a complicated regex to match the release on the [Sonarqube downloads](https://www.sonarqube.org/downloads/) page.

I'll create a PR that closes this shortly.
